{
 "title": "SNMP / Ubiquiti / WiFi",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{job=~\"snmp.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Devices",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "device_interfaces",
    "label": "Interface",
    "query": {
     "query": "query_result(ifOperStatus{job=~\"$job\",instance=~\"$instance\"}==1)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(unifiApSystemModel{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemModel)"
    }
   },
   {
    "name": "device_firmware_version",
    "query": {
     "query": "label_values(unifiApSystemVersion{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemVersion)"
    }
   },
   {
    "name": "device_mac_addresses",
    "query": {
     "query": "label_values(ifPhysAddress{job=~\"$job\",instance=~\"$instance\"}, ifPhysAddress)"
    }
   },
   {
    "name": "device_main_ip",
    "query": {
     "query": "label_values(unifiApSystemIp{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemIp)"
    }
   },
   {
    "name": "device_ESSIDs",
    "label": "Interface",
    "query": {
     "query": "label_values(unifiVapEssId{job=~\"$job\",instance=~\"$instance\"}, unifiVapEssId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic on the air",
   "type": "graph",
   "description": "This is the global overview of all wireless traffic coming from and going to the access points.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the air",
   "type": "graph",
   "description": "This is the global overview of all wireless traffic coming from and going to the access points.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  {
   "title": "Traffic on the wire",
   "type": "graph",
   "description": "This is the global overview of all traffic coming from and going to the access points through the wired network.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"eth.*\"}[$__rate_interval]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"eth.*\"}[$__rate_interval]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the wire",
   "type": "graph",
   "description": "This is the global overview of all packets coming from and going to the access points through the wired network.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiIfRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiIfRxMulticast{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, multicast"
    },
    {
     "expr": "sum(rate(unifiIfRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiIfRxError{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, error"
    },
    {
     "expr": "sum(rate(unifiIfTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiIfTxMulticast{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, multicast"
    },
    {
     "expr": "sum(rate(unifiIfTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiIfTxError{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, error"
    }
   ]
  },
  {
   "title": "Models",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "options": {
    "content": "Models: $device_model  \nFirmware versions: $device_firmware_version  \n"
   },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$instance ESSIDs",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "options": { "content": "$device_ESSIDs" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "Worst 3 response times by devices",
   "type": "graph",
   "description": "If any device is consistently above the others, this might indicate a problem. Consider rebooting that device, upgrading it, or putting another one nearby to reduce load.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3,scrape_duration_seconds{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "devices" },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Traffic on air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  }
 ]
}