{
 "title": "SNMP / Ubiquiti Access Point",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{job=~\"snmp.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Devices",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "device_interfaces",
    "label": "Interface",
    "query": {
     "query": "query_result(ifOperStatus{job=~\"$job\",instance=~\"$instance\"}==1)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(unifiApSystemModel{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemModel)"
    }
   },
   {
    "name": "device_firmware_version",
    "query": {
     "query": "label_values(unifiApSystemVersion{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemVersion)"
    }
   },
   {
    "name": "device_mac_addresses",
    "query": {
     "query": "label_values(ifPhysAddress{job=~\"$job\",instance=~\"$instance\"}, ifPhysAddress)"
    }
   },
   {
    "name": "device_main_ip",
    "query": {
     "query": "label_values(unifiApSystemIp{job=~\"$job\",instance=~\"$instance\"}, unifiApSystemIp)"
    }
   },
   {
    "name": "device_ESSIDs",
    "label": "Interface",
    "query": {
     "query": "label_values(unifiVapEssId{job=~\"$job\",instance=~\"$instance\"}, unifiVapEssId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic on the air",
   "type": "graph",
   "description": "How much traffic is on the air and going through this particular access point?",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapTxBytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the air",
   "type": "graph",
   "description": "How many packets are on the air and going through this particular access point?\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifiVapRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(unifiVapRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(rate(unifiVapRxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(rate(unifiVapTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(unifiVapTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(rate(unifiVapTxErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  {
   "title": "Traffic on the wire",
   "type": "graph",
   "description": "How much traffic is coming from and going to this particular access point into the wired network?\n\nIf this empty, the access point is likely in wireless relay mode.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"eth.*\"}[$__rate_interval]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"eth.*\"}[$__rate_interval]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the wire",
   "type": "graph",
   "description": "How many packets are coming from and going to this particular access point into the wired network?\n\nIf this empty, the access point is likely in wireless relay mode.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(unifiIfRxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(unifiIfRxMulticast{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "In, multicast"
    },
    {
     "expr": "rate(unifiIfRxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "rate(unifiIfRxError{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "In, error"
    },
    {
     "expr": "rate(unifiIfTxPackets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(unifiIfTxMulticast{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Out, multicast"
    },
    {
     "expr": "rate(unifiIfTxDropped{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "rate(unifiIfTxError{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Out, error"
    }
   ]
  },
  { "title": "Health & info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load average",
   "type": "graph",
   "description": "This is the Linux load average as per https://en.wikipedia.org/wiki/Load_(computing)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "laLoadFloat{job=~\"$job\",instance=~\"$instance\",laIndex=\"1\"}",
     "legendFormat": "1 minute"
    },
    {
     "expr": "laLoadFloat{job=~\"$job\",instance=~\"$instance\",laIndex=\"2\"}",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "laLoadFloat{job=~\"$job\",instance=~\"$instance\",laIndex=\"3\"}",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{job=~\"$job\",instance=~\"$instance\"} - memTotalFree{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Used, absolute"
    },
    {
     "expr": "(memTotalReal{job=~\"$job\",instance=~\"$instance\"} - memTotalFree{job=~\"$job\",instance=~\"$instance\"}) / memTotalReal{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Used, relative"
    }
   ]
  },
  {
   "title": "$instance information",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
   "options": {
    "content": "Model: $device_model  \nFirmware: $device_firmware_version  \nMain IP: $device_main_ip\n\n"
   },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$instance ESSIDs",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 40 },
   "options": { "content": "${device_ESSIDs}" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$instance MAC",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "options": { "content": "$device_mac_addresses" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "Job response times",
   "type": "graph",
   "description": "This is split into the internal parts of snmp_exporter to show where any timing problems come from.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Total job, Prometheus point of view"
    },
    {
     "expr": "snmp_scrape_duration_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "snmp_exporter, internal"
    },
    {
     "expr": "snmp_scrape_walk_duration_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "snmp_exporter, just SNMP"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "repeat": "device_interfaces",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=\"$device_interfaces\"}[$__rate_interval]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  }
 ]
}